// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { PingError, PingResponse } from './types.gen';

export const client = createClient(createConfig());

export class Umbraco15ContentModelsService {
    public static ping<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<PingResponse, PingError, ThrowOnError>({
            ...options,
          url: '/umbraco/umbraco15contentmodels/api/v1/ping'
        });
    }
}
